"""empty message

Revision ID: 069939575466
Revises: a55e46b42d9f
Create Date: 2019-10-07 15:11:05.092010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069939575466'
down_revision = 'a55e46b42d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('four', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('one', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('three', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('two', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('win_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'win_img')
    op.drop_column('games', 'two')
    op.drop_column('games', 'three')
    op.drop_column('games', 'one')
    op.drop_column('games', 'four')
    # ### end Alembic commands ###
