"""empty message

Revision ID: 3e8adf707a4a
Revises: c41fe5b542aa
Create Date: 2019-10-09 09:57:54.860619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8adf707a4a'
down_revision = 'c41fe5b542aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('t1', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t10', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t11', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t12', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t13', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t14', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t15', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t16', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t2', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t3', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t4', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t5', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t6', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t7', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t8', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('t9', sa.Integer(), nullable=True))
    op.drop_column('games', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 't9')
    op.drop_column('games', 't8')
    op.drop_column('games', 't7')
    op.drop_column('games', 't6')
    op.drop_column('games', 't5')
    op.drop_column('games', 't4')
    op.drop_column('games', 't3')
    op.drop_column('games', 't2')
    op.drop_column('games', 't16')
    op.drop_column('games', 't15')
    op.drop_column('games', 't14')
    op.drop_column('games', 't13')
    op.drop_column('games', 't12')
    op.drop_column('games', 't11')
    op.drop_column('games', 't10')
    op.drop_column('games', 't1')
    # ### end Alembic commands ###
