"""empty message

Revision ID: 450bae7865cc
Revises: 3e8adf707a4a
Create Date: 2019-10-09 13:55:32.589605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450bae7865cc'
down_revision = '3e8adf707a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('games', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
