"""empty message

Revision ID: 9c3919518d49
Revises: 7cf573cd3e1d
Create Date: 2019-10-04 09:40:35.072448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3919518d49'
down_revision = '7cf573cd3e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pieces_beginner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_beginner')
    # ### end Alembic commands ###
